# Generated by Django 5.1.5 on 2025-02-05 14:03

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=256)),
                ('patterns', django_mysql.models.ListCharField(models.CharField(max_length=256), max_length=256, size=None)),
                ('responses', django_mysql.models.ListCharField(models.CharField(max_length=256), max_length=256, size=None)),
            ],
        ),
    ]
