# Generated by Django 5.1.5 on 2025-02-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='intent',
            table='intents',
        ),
    ]
